#!/bin/sh
cat <<EOF > /usr/share/nginx/html/config.js
window.env = {
  VITE_APP_SENTRY_DSN: '$VITE_APP_SENTRY_DSN',
  VITE_APP_SERVER_URL: '$VITE_APP_SERVER_URL',
  VITE_APP_CLIENT_URL: '$VITE_APP_CLIENT_URL',
  VITE_APP_GT4_MEASUREMENT_ID: '$VITE_APP_GT4_MEASUREMENT_ID',
  VITE_APP_AWS_S3_BUCKET: '$VITE_APP_AWS_S3_BUCKET'
};
EOF
